container: homeassistant/home-assistant:dev
created: 2019-08-09 20:53:53.501852
name: home-assistant
ports:
        8123/tcp: 8123
        8300/tcp: 8300
        8555/tcp: 8555
        51827/tcp: 51827
volumes:
        /etc/home-assistant/config:
                bind: /config
                mode: rw
        /etc/localtime:
                bind: /etc/localtime
                mode: ro
privileged: false
tty: false
environment: {}
network_mode: bridge
working_dir: /usr/src/app
